name: Generate Pacman Contribution Game

on:
  schedule:
    - cron: "0 12 * * *"  # Runs daily at noon UTC (better visibility than midnight)
  workflow_dispatch:      # Allows manual triggering
  push:
    branches:
      - main              # Runs on pushes to main branch

jobs:
  generate-pacman:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Needed to commit the SVG back to repo
    
    steps:
      - uses: actions/checkout@v4
      
      # Using the most reliable and customizable action
      - name: Generate Pacman SVG
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: "diogocarrola"            # Your GitHub username
          github_token: ${{ secrets.GITHUB_TOKEN }}   # Token for authentication
      
      # Move and rename the file
      - name: Prepare assets
        run: |
          mkdir -p assets
          mv pacman-contribution-graph.svg assets/pacman-contributions.svg
      
      # Verify generation
      - name: Verify SVG
        run: |
          if [ ! -s "assets/pacman-contributions.svg" ]; then
            echo "Error: SVG file not generated"
            exit 1
          fi
          echo "SVG generated successfully"

      # Commit directly to main (simpler than pages)
      - name: Commit and Push
        run: |
          git config --global user.name "diogocarrola-bot"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/pacman-contributions.svg
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update Pacman contribution game" && git push)