name: Update Pacman Contribution Graph

on:
  schedule:
    - cron: "0 12 * * *"  # Daily at 12:00 UTC
  workflow_dispatch:      # Manual trigger

jobs:
  update-pacman:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone Pacman Contribution Graph fork
        run: |
          git clone https://github.com/diogocarrola/pacman-contribution-graph.git

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: pacman-contribution-graph

      - name: Build project
        run: npm run build
        working-directory: pacman-contribution-graph

      - name: Generate Pacman SVG
        run: |
          node dist/index.js --username=${{ github.repository_owner }} --output=svg --theme=github > ../assets/pacman-contributions.svg
          node dist/index.js --username=${{ github.repository_owner }} --output=svg --theme=github-dark > ../assets/pacman-contributions-dark.svg
        working-directory: pacman-contribution-graph

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/pacman-contributions.svg
          git add assets/pacman-contributions-dark.svg
          git commit -m "Update Pacman contribution visualization" || echo "No changes to commit"
          git push